{block #title}Administrace{/block}
{block #content}

<p>Zde můžete přidávat práce a autory.</p>
<p>Nového autora můžete přidat s jeho první prací a další jeho práce pak k němu
přirazovat. Program si pamatuje údaje poslední přidané práce, takže můžete lehce
přidávat další práce stejného autora, ve stejném ročníku atd.</p>
<p>V seznamech se dá řadit i filtrovat tak jako na webu.</p>
<p>Jméno a příjmení autora není potřeba uvádět s velkými písmeny, program se o
to sám postará.</p>
<p>K odhlášení dojde pokud zavřete prohlížeč nebo kliknete na odhlásit.</p>
